spring:
  application:
    name: gateway
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888/
      discovery:
        serviceId: config-server
        enabled: true
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            #allowedOrigins: "http://localhost:5173"
            allowedOrigins: "http://localhost:3000"
            #allowedHeaders: '*'
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - Origin
              - X-Requested-With
              - Content-Type
              - Accept
              - Authorization
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: users-service
          #uri: http://users-service:8081
          uri: lb://users-service
          predicates:
            - Path=/user/**
        - id: accounts-service
          #uri: http://accounts-service:8082
          uri: lb://accounts-service
          predicates:
            - Path=/account/**

management:
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    env:
      enabled: true
info:
  app:
    name: Gateway
    description: API gateway
    version: 1.0.0

eureka:
  instance:
    hostname: localhost
    statusPageUrlPath: http://localhost:8084/actuator/info
    healthCheckUrlPath: http://localhost:8084/actuator/info
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


server:
  port: 8084